# A unique key for your project in SonarQube
sonar.projectKey=e-corp-demo_nodejs-goof_262304f3-9804-4b7b-8162-9b7400a6d47b

# The name of the project that will be displayed in SonarQube
sonar.projectName=nodejs-goof

# The version of your project
sonar.projectVersion=1.0

# Path to the source code to be analyzed
sonar.sources=.

# Exclude node_modules and other irrelevant files
sonar.exclusions=node_modules/**, build/**

# Language of the project
sonar.language=js

# Encoding of the source code
sonar.sourceEncoding=UTF-8
