name: "snyk code test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: snyk code test --org=2926939e-40c9-407e-ac64-14137a47b39c --sarif > snyk-sarif2.json
        continue-on-error: true
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
