name: "snyk code test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: snyk code test --org=26891985-3294-4d0f-939b-4d1f88b6c892
        continue-on-error: false
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
           #SNYK_API: https://api.eu.snyk.io
